name: Commit Format

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    paths-ignore:
      - "nuxt/**"

jobs:
  dry-release:
    runs-on: ubuntu-latest

    outputs:
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
  
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - uses: cycjimmy/semantic-release-action@e1fe1fc00a3729593e87efb2f88475de76d64a24
        id: semantic
        with:
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: mshick/add-pr-comment@07f690343c25a94e24a8acb70d03c86b701ae322
        name: Comment on PR
        if: ${{ !steps.semantic.outputs.new_release_published }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Please note, you PR will not generate a new release.

            If you want it to create a new release, you commits should follow the convention:

            Examples:

            ```
            Breaking: I broke something
            Fix: fix (fixes #1234)
            Update: some packages updates (refs #123)
            New: Added a new feature
            ```

            See more in `release.config.js`.
