name: Build/Release

on:
  push:
    branches: release
    paths-ignore:
      - "nuxt/**"

jobs:
  release:
    runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2
    - run: yarn semantic-release