name: Build/Release

on:
  push:
    branches:
    - release
    paths-ignore:
      - "nuxt/**"

jobs:
  release:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}